### ISSUE TITLE
Question about color channel order (gray background) in video demos

### ISSUE THREAD

**Issue by DeeDive** [cliport/cliport#11]
Hi, thanks for the great work! I am new to OpenCV and I feel a little bit confused about the channel order for your video. The visualization replicated by myself has yellow background instead of the gray background in your demos. Is there anything wrong with my color channels? Or did you manually edit those rendered videos? Millions of thanks in advance.

**Comment by MohitShridhar** [comment]
@DeeDive, all the simulation videos for the website were recorded with the `record.save_video=True` option. I just added some instructions here: https://github.com/cliport/cliport#recording-videos

Regarding the yellow background in PyBullet: I have also noticed this sometimes. I am not sure what is happening here because the rendered videos seem fine. You might have to mess around with the [plane asset](https://github.com/cliport/cliport/tree/master/cliport/environments/assets/plane) to fix this.

**Comment by DeeDive** [comment]
Yeah, thanks for your explanation! I find that there is no color specified in the [plane.urdf](https://github.com/cliport/cliport/blob/master/cliport/environments/assets/plane/plane.urdf). It is wired that if you turn the render=True, then the background will be yellow in the window opened pybullet. But actually, the video saver uses the same observation image... However, other objects' colors remain unaffected.

**Comment by MohitShridhar** [comment]
Have you tried `record.save_video=True` with `disp=False`? Do the recorded videos still have a yellow background?

Actually, I am not too familiar with PyBullet, so maybe check here: https://pybullet.org/Bullet/phpBB3/ ?
